### ISSUE TITLE
Add current boundaries from Census

### ISSUE THREAD

**Issue by lmullen** [ropensci/USAboundaries#10]
This will probably take the form of a new function `us_current_boundaries()` that provides state, county, ZIP code, and other boundaries from the census. The state and country boundary data will live directly in this package. The ZIP code and metropolitan area data will be in a separate data only package, since they are much larger. But they will be accessed through the same function.

**Comment by hadley** [comment]
What about making `us_boundaries()` (with no date) correspond to the current (latest) maps?

**Comment by hadley** [comment]
If you didn't want to do everything in one function, I'd suggest map `us_states()`, `us_counties()`, `us_zips()` etc. Then us_boundaries could stay as a wrapper:

```R
s_boundaries <- function(map_date, type = c("state", "county", "zip"),
                          states = NULL) {

  type <- match.arg(type)
  switch(type,
     state = us_states(map_date, states),
     counties = us_counties(map_date, state),
     zip = us_zips(map_date, state)
  )
```

**Comment by lmullen** [comment]
Yes, I like the idea of no date corresponding to the current boundaries. I'd much prefer to keep everything in a single function, with unexported functions as necessary.

**Comment by hadley** [comment]
I don't feel strongly either way - but I think having different functions for different boundary types is slightly more evocative, and makes it a bit easier to extend in the future

**Comment by lmullen** [comment]
That makes sense; no harm in exporting functions for different boundary types.

I'm also going to add a resolution argument: `us_boundaries(resolution = c("500k", "5m", "20m"))`. Only the lowest resolution files will be in this package; higher resolutions will be available in package in `Suggests`.

**Comment by hadley** [comment]
I like it.  I think it's worth trying to get the higher-res packages on CRAN - let me know before you submit and I can help craft the submission comments.  If that fails, a drat repo should be fine, esp. since I think everyone can now install source packages that don't require compilation.

**Comment by lmullen** [comment]
Will do.

**Comment by lmullen** [comment]
Implemented in branch `newinterface`, coming to master soon.

**Comment by hadley** [comment]
Woooo - thanks!
