### ISSUE TITLE
Get USAboundaries and USAboundariesData on CRAN

### ISSUE THREAD

**Issue by lmullen** [ropensci/USAboundaries#20]
@hadley Can I take you up on your offer to look at the CRAN comments for these two packages?

I need to do all the final checks before submitting to CRAN, but other than that I think I'm done with these two packages. The only sticking point for the CRAN submission is that USAboundariesData is 48.8 Mb. Do you have any thoughts on how to persuade CRAN?

- [CRAN comments for USAboundaries](https://github.com/ropensci/USAboundaries/blob/master/cran-comments.md)
- [CRAN comments for USAboundariesData](https://github.com/ropensci/USAboundariesData/blob/master/cran-comments.md)

**Comment by hadley** [comment]
How much of a difference would it make if you split the data package into historical and modern datasets?

**Comment by lmullen** [comment]
It might be worth doing. The historical data is only about 2.4 Mb. But I'd like to add higher resolution versions, which will add quite a bit. (If I do that, then the resolution argument will change from `resolution = c("20m", "5m", "500k")` to `resolution = c("low", "med", "high")`. But the contemporary data will have to change every year, whereas the historical will never change. 

The single biggest file is the zip codes, which is 32 Mb.

**Comment by hadley** [comment]
Hmmmmm, maybe separate out the zipcodes? CRAN is definitely not going to go for a 30 meg package that gets updated every year. 

Bigger data packages can go as drat() repos - and you can include notes describing how to install, or provide a helper function that calls `install.packages()` with the right arguments. Does that make sense?

**Comment by lmullen** [comment]
Thanks for the suggestion, @hadley. I have the same basic problem with the gender package. But it looks like rOpenSci has a [drat repository up and running](https://github.com/ropensci/genderdata/issues/5). I think I might try that approach first for the data only packages, which will give me more flexibility about adding and extending, then just put the interface package on CRAN.

**Comment by hadley** [comment]
I'd recommend putting at least one data package on cran - then the package can do something straight away. And have examples etc.

**Comment by lmullen** [comment]
This issue is fixed in the latest release. I included the contemporary and historical low-res data in the CRAN package, which can install a package with higher-resolution data from the rOpenSci repository.

**Comment by hadley** [comment]
Perfect :smile:
