### ISSUE TITLE
Ohio 9th congressional district

### ISSUE THREAD

**Issue by CaDaBu** [ropensci/USAboundaries#25]
Hello,

First let me thank you for developing such a wonderful data set. I have found it to be most useful. I did notice a mistake in the congressional boundaries for Ohio's 9th district in both the high resolution data set and the low data resolution set. The boundaries in each case only covered a small subset of the district. It is a strange district on the edge of the lake which makes it hard to draw I'm sure.

Best wishes

**Comment by lmullen** [comment]
@CaDaBu Those boundaries are provided by the Census Bureau. Have you checked the Census shapefiles linked in the documentation to see whether they are accurate?

**Comment by CaDaBu** [comment]
No I haven't. How do I find those shape files?

**Comment by lmullen** [comment]
Please check the documentation in this package: `?census_boundaries`. The link is provided there.
