### ISSUE TITLE
County ID

### ISSUE THREAD

**Issue by CaDaBu** [ropensci/USAboundaries#26]
Hello,

I made a spatialpolygondatafram at the congressional level and was hoping to match these counties to FIPS county codes. 

I saw that the spatialpolygondataframe had an ID slot. I looked at the ID slot for the counties in Ohio. I could not tell what they were or which entry in the object corresponded to which county. 

Can you tell me what these slot IDs mean and how to match them with the correct FIPS code for each county?

Here is part of my code:

ohiocount<-us_boundaries(type="county",resolution="high",state="Ohio")
x<-c();for(i in 1:88){x[i]<-ohiocount@polygons[[i]]@ID}
x

**Comment by lmullen** [comment]
Please take a look at the data frame embedded in the `SpatialPolygonsDataFrame` object. E.g.

```
ohiocount@data
colnames(ohiocount@data)
```

You'll see that there is a state FIPS code, a county FIPS code, and a GEOID that puts them together.
