### ISSUE TITLE
Add local legislative districts

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/USAboundaries#27]
State senate and house (or upper/lower) districts are available over time at https://www.census.gov/geo/maps-data/data/cbf/cbf_sld.html

Can they be incorporated?

I seem to remember finding a site that tried to get them back into the 1800s, but my google-fu is failing me.

**Comment by lmullen** [comment]
I will consider adding these the next time I update this package.

**Comment by lmullen** [comment]
This functionality is available in the tigris package. https://cran.rstudio.com/web/packages/tigris/
