### ISSUE TITLE
Albers USA projection

### ISSUE THREAD

**Issue by lmullen** [ropensci/USAboundaries#33]
Get an Albers USA projection the same way that you can get state plane projections.

**Comment by lmullen** [comment]
@hrbrmstr's way of doing this. https://github.com/hrbrmstr/rd3albers

**Comment by hrbrmstr** [comment]
also https://github.com/hrbrmstr/albersusa

**Comment by lmullen** [comment]
@hrbrmstr That package looks fantastic! Hope it is on CRAN soon.
