### ISSUE TITLE
add states argument to `us_cities()` and `us_zipcodes()`

### ISSUE THREAD

**Issue by AndySouth** [ropensci/USAboundaries#35]
`us_cities()` and `us_zipcodes()` don't yet offer states argument as indicated in the readme. Can they be added ?

**Comment by lmullen** [comment]
I have made `us_cities()` accept a `states` argument. Zip codes can cross state boundaries so that is not possible for `us_zipcodes()`. But I have updated to the README to make it clear that most but not all functions accept the `states` argument.
