### ISSUE TITLE
Can us_cities() return an sf object ?

### ISSUE THREAD

**Issue by AndySouth** [ropensci/USAboundaries#36]
Is there a reason that us_cities returns a dataframe and not an sf points object ? Returning as an sf object would help us_cities() being used in combination with us_states(). I tried sf::plot(st_geometry(us_cities())) expecting it to work the same as us_states(). 

Also can use of us_cities() be added to the readme ?

**Comment by lmullen** [comment]
This was changed in the USAboundariesData package and `USAboundaries::us_cities()` now returns an sf data.frame.
