### ISSUE TITLE
Deprecation of us_boundaries

### ISSUE THREAD

**Issue by donojazz** [ropensci/USAboundaries#46]
"Remove legacy us_boundaries() function" - Oct 8

Looks like us_boundaries() was removed.  Reference still in master documents.  Broke code on a major geospatial reference book.
https://geocompr.robinlovelace.net/adv-map.html

Which function replaced it?

Thanks

**Comment by lmullen** [comment]
@donojazz You can use the equivalent function for the type of geography that you want to use. For instance, `us_states()` for state boundaries. The function arguments should be easily transferable. 

You might also consider using the older version of the package if you wish. The package version numbers are semantically versioned.
