### ISSUE TITLE
Issues downloading from github

### ISSUE THREAD

**Issue by FelipeCarrillo** [ropensci/USAboundaries#49]
Hi;
Is there an alternate site where I can download USAboundaries or USAboundariesData? I tried both options and got the following error messages:
> remotes::install_github("ropensci/USAboundaries")
Downloading GitHub repo ropensci/USAboundaries@HEAD
Running `R CMD build`...

STDOUT:

STDERR:
Error in library(USAboundaries) : 
  there is no package called 'USAboundaries'
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
In addition: There were 13 warnings (use warnings() to see them)
Execution halted
Error: Failed to install 'USAboundaries' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.

I am using R 4.1

**Comment by lmullen** [comment]
Installing from GitHub works fine for me:

```
remotes::install_github("ropensci/USAboundaries")
remotes::install_github("ropensci/USAboundariesData")
```

Please try again. If it continues to not work, please follow this line and share the additional warnings.

```
In addition: There were 13 warnings (use warnings() to see them)
```

You can also try installing from the ROpenSci CRAN-like repository:

```
install.packages("USAboundaries", repos = "https://ropensci.r-universe.dev")
install.packages("USAboundariesData", repos = "https://ropensci.r-universe.dev")
```
