### ISSUE TITLE
Fix slack notifications for @ropensci

### ISSUE THREAD

**Issue by lmullen** [ropensci/USAboundaries#5]
See error message [here](https://ci.appveyor.com/project/lmullen/usboundaries/build/1.0.136), for example.

**Comment by sckott** [comment]
both appveyor and travis aren't working, right?

**Comment by lmullen** [comment]
CRAN required me to change the package name, and hence the repo name, from usboundaries to USAboundaries. Either Travis caught that automatically or I fixed it, but I neglected to fix it for Appveyor. Do I have the wrong key in the Appveyor/Travis files?

**Comment by lmullen** [comment]
@sckott What is a good @ropensci repo to copy the Slack configurations from?

**Comment by sckott** [comment]
maybe this one for travis https://github.com/ropensci/geojsonio/blob/master/.travis.yml
