### ISSUE TITLE
Reduce imports

### ISSUE THREAD

**Issue by hadley** [ropensci/USAboundaries#8]
Currently you have:

```R
Imports:
    assertthat (>= 0.1),
    dplyr (>= 0.3.0.1),
    ggplot2 (>= 1.0.0),
    lubridate (>= 1.3.3),
    maptools (>= 0.8-30),
    rgeos (>= 0.3-8),
    sp (>= 1.0.15)
```

I think you could eliminate quite a few of these:

* ggplot2 and dplyr (I think) are only used in the vignette, so could be move to the suggests
* I don't see where rgeos is used
* I think you could replace `lubridate::ymd` with `as.Date()`

**Comment by lmullen** [comment]
Yes, you're right that most of these imports are unnecessary, @hadley. I used ggplot2 to fortify objects from the `sp` package into data frames, but I'm not sure that's a feature that needs to be included in this package. If people need to do that, they can do it for themselves. I'll see about cleaning up the dependencies.

**Comment by lmullen** [comment]
The package now only imports the sp package. After I'm sure this update works with another project, I'll send this version to CRAN.

**Comment by hadley** [comment]
Thanks! BTW we're working on https://github.com/AndySouth/rnaturalearth - so we'll try and match the API in your package.

Do you know of a good package for current US boundaries? (state, county, zip etc)

**Comment by lmullen** [comment]
Nice! A Natural Earth package will be very useful.

I've used the maps package for quick maps of state boundaries, but I'm not sure how up to date it is. I can see about using Census shapefiles for current boundaries. That might be a good addition to this package. Let me see whether I can fit those in without bumping into the CRAN size limit.

**Comment by sckott** [comment]
there's a variety of geojson data sources on github:

* https://github.com/johan/world.geo.json/tree/master/countries/USA
* http://eric.clst.org/Stuff/USGeoJSON
* https://github.com/glynnbird/usstatesgeojson
* congressional districts https://github.com/unitedstates/districts/tree/gh-pages/cds

**Comment by hadley** [comment]
@sckott I think the canonical source for raw data is https://www.census.gov/geo/maps-data/data/tiger-cart-boundary.html

**Comment by sckott** [comment]
right, just thinking geojson easier to deal with

**Comment by lmullen** [comment]
@hadley How are you getting around the 5 MB limit for CRAN packages for rnaturalearth? I'm thinking about a separate data package stored in a drat repository.

**Comment by hadley** [comment]
It's usually easier to argue the case for a data only package. There are quite a few bigger than 5 meg.
